Acordar;
Abrir os olhos;
Levantar o celular do gaveteiro;
Ligar a tela do celular;
Se o celular estiver com a carga abaixo de 100%;
    Manter o celular plugado ao carregador;
    levantar da cama;
Se o celular estiver com a carga 100%
    desplugar o carregador do celular;
    colocar o celular no bolso;
    levantar da cama;
Caminhar até a mesa;
Ligar o computador;
Ligar os monitores;
Caminhar até a porta do quarto;
Colocar a mão na maçaneta;
Girar a maçaneta em 90 graus;
Puxar a porta;
Ir até o banheiro;
Caminhar até a porta do banheiro;
Colocar a mão na maçaneta;
Girar a maçaneta em 90 graus;
Empurrar a porta;
Entrar no banheiro;
Caminhar até o espelho;
Pegar escova de dentes;
Passar pasta dentaria na escova de dentes;
Abrir a torneiro da pia;
Colocar água na mão;
Levar a mão até a boca;
abrir boca;
Colocar água dentro da boca;
Bochechar a água dentro da boca;
Cuspir a água dentro da pia;
Escovar os dentes;
Escovar a língua;
Se a boca estiver com espuma de pasta dentaria;
    Cuspir espuma dentro da pia;
    Colocar água na mão;
    Levar a mão até a boca;
    abrir boca;
    Colocar água dentro da boca;
    Bochechar a água dentro da boca;
    Cuspir a água dentro da pia;
Lavar o rosto com água;
Pegar uma toalha de rosto;
secar o rosto;
Caminhar até a porta do banheiro;
Colocar a mão na maçaneta;
Girar a maçaneta em 90 graus;
Puxar a porta;
Caminhar até cozinha;
Se estiver com fome;
    Pegar 3 ovos;
    Azeite;
    Frigideira;
    Colocar a Frigideira na boca fogão;
    Ligar a boca do fogão;
    tirar tampa do azeite;
    Colocar o azeite na frigideira;
    Esperar esquentar o azeite;
    Se o azeite não estiver quente;
        Esperar até esquentar;
    Se o azeite estiver quente;
        Quebrar os ovos;
        Despejar os ovos na frigideira;
    Enquanto espera os ovos ficarem prontos;
    Abrir gaveta de talheres;
    Pegar uma faca de serra;
    Pegar pão;
    Cortar o pão ao meio com a faca de serra;
    abrir o pão;
    colocar o pão no prato;
    Se os ovos não estiverem prontos;
        esperar os ovos ficarem prontos;
    Se os ovos estiverem prontos;
        Pegar espatula; 
        colocar os ovos dentro do pão com a espatula;
        Fechar pão;
        Comer;
Se não estiver com fome;
    Voltar pro quarto;
    ligar a luz;
    Caminhar até estante de livros;
    Pegar livro;
    Ler;
Fim.


